PortalDeNoticias/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PortalDeNoticias.Models;


namespace PortalDeNoticias.Controllers
{
    public class NoticiasController : Controller
    {
        // GET: Noticias
        public ActionResult Index()
        {
            return View(Repositorio.ListadeNoticia1);
        }

        public ActionResult Detalhes(int id)

        {
            var noticiaSelecionada = Repositorio.ListadeNoticia1.FirstOrDefault(not => not.Id == id);
            return View(noticiaSelecionada);
        }

        public ActionResult Buscar(string texto)
        {
            var noticiasEncontrada = Repositorio.ListadeNoticia1.Where(not => not.Titulo.Contains(texto)
            || not.Conteudo.Contains(texto));
            return View(noticiasEncontrada);
        }
    }



}

PortalDeNoticias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Portal de Noticias</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1>Portal De Noticias</h1>
        </div>
        <div class="navbar navbar-inverse navbar-fixed-top">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pagina Incial", "Index", "Noticias", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <p class="panel-title">Buscar</p>
                        <div class="panel-body">
                           @using (Html.BeginForm("Buscar", "Noticias", FormMethod.Get))
                            {
                                <input type="text" name="texto" placeholder="Buscar por..." class="form-control" />
                            }   

                        </div>
                    </div>
                </div>
            </div>    
        
        </div>



        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Portal de noticias</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>